version: '3.3'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: triathlon-backend
    # Порт не экспонируется наружу для безопасности - доступ только через Nginx
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./triathlon_training.db
      - CORS_ORIGINS=http://localhost,http://localhost:80,http://localhost:3000,http://frontend:3000,http://nginx:80
    volumes:
      - backend-data:/app/data
    networks:
      - triathlon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: triathlon-frontend
    # Порт не экспонируется наружу - доступ только через Nginx
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=  # В продакшене API доступен через тот же домен (Nginx)
    depends_on:
      - backend
    networks:
      - triathlon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: triathlon-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - triathlon-network
    restart: unless-stopped

networks:
  triathlon-network:
    driver: bridge

volumes:
  backend-data:
    driver: local
